<?php 
 $cyber_reputation_class = [
 ["sic_code" => 1,"industry_title" => "Agricultural Production - Crops","reputation_class" => 2,],
["sic_code" => 2,"industry_title" => "Agricultural Production - Livestock","reputation_class" => 2,],
["sic_code" => 7,"industry_title" => "Agricultural Services","reputation_class" => 1,],
["sic_code" => 8,"industry_title" => "Forestry","reputation_class" => 1,],
["sic_code" => 9,"industry_title" => "Fishing. Hunting. & Trapping","reputation_class" => 1,],
["sic_code" => 10,"industry_title" => "Metal. Mining","reputation_class" => 1,],
["sic_code" => 12,"industry_title" => "Coal Mining","reputation_class" => 1,],
["sic_code" => 13,"industry_title" => "Oil & Gas Extraction","reputation_class" => 1,],
["sic_code" => 14,"industry_title" => "Nonmetallic Minerals. Except Fuels","reputation_class" => 1,],
["sic_code" => 15,"industry_title" => "General Building Contractors","reputation_class" => 3,],
["sic_code" => 16,"industry_title" => "Heavy Construction. Except Building","reputation_class" => 2,],
["sic_code" => 17,"industry_title" => "Special Trade Contractors","reputation_class" => 3,],
["sic_code" => 20,"industry_title" => "Food & Kindred Products","reputation_class" => 3,],
["sic_code" => 21,"industry_title" => "Tobacco Products","reputation_class" => 2,],
["sic_code" => 22,"industry_title" => "Textile Mill Products","reputation_class" => 2,],
["sic_code" => 23,"industry_title" => "Apparel & Other Textile Products","reputation_class" => 2,],
["sic_code" => 24,"industry_title" => "Lumber & Wood Products","reputation_class" => 2,],
["sic_code" => 25,"industry_title" => "Furniture & Fixtures","reputation_class" => 2,],
["sic_code" => 26,"industry_title" => "Paper & Allied Products","reputation_class" => 2,],
["sic_code" => 27,"industry_title" => "Printing & Publishing","reputation_class" => 3,],
["sic_code" => 28,"industry_title" => "Chemical & Allied Products","reputation_class" => 2,],
["sic_code" => 29,"industry_title" => "Petroleum & Coal Products","reputation_class" => 2,],
["sic_code" => 30,"industry_title" => "Rubber & Miscellaneous Plastics Products","reputation_class" => 2,],
["sic_code" => 31,"industry_title" => "Leather & Leather Products","reputation_class" => 2,],
["sic_code" => 32,"industry_title" => "Stone. Clay. & Glass Products","reputation_class" => 2,],
["sic_code" => 33,"industry_title" => "Primary Metal Industries","reputation_class" => 2,],
["sic_code" => 34,"industry_title" => "Fabricated Metal Products","reputation_class" => 2,],
["sic_code" => 35,"industry_title" => "Industrial Machinery & Equipment","reputation_class" => 2,],
["sic_code" => 36,"industry_title" => "Electronic & Other Electric Equipment","reputation_class" => 2,],
["sic_code" => 37,"industry_title" => "Transportation Equipment","reputation_class" => 2,],
["sic_code" => 38,"industry_title" => "Instruments & Related Products","reputation_class" => 2,],
["sic_code" => 39,"industry_title" => "Miscellaneous Manufacturing Industries","reputation_class" => 2,],
["sic_code" => 40,"industry_title" => "Railroad Transportation","reputation_class" => 3,],
["sic_code" => 41,"industry_title" => "Local & Interurban Passenger Transit","reputation_class" => 3,],
["sic_code" => 42,"industry_title" => "Trucking & Warehousing","reputation_class" => 3,],
["sic_code" => 43,"industry_title" => "US Postal Service","reputation_class" => 2,],
["sic_code" => 44,"industry_title" => "Water Transportation","reputation_class" => 2,],
["sic_code" => 45,"industry_title" => "Transportation by Air","reputation_class" => 3,],
["sic_code" => 46,"industry_title" => "Pipelines. Except Natural Gas","reputation_class" => 2,],
["sic_code" => 47,"industry_title" => "Transportation Services","reputation_class" => 2,],
["sic_code" => 48,"industry_title" => "Communications","reputation_class" => 3,],
["sic_code" => 49,"industry_title" => "Electric. Gas. & Sanitary Services","reputation_class" => 2,],
["sic_code" => 50,"industry_title" => "Wholesale Trade - Durable Goods","reputation_class" => 2,],
["sic_code" => 51,"industry_title" => "Wholesale Trade - Nondurable Goods","reputation_class" => 2,],
["sic_code" => 52,"industry_title" => "Building Materials & Gardening Supplies","reputation_class" => 2,],
["sic_code" => 53,"industry_title" => "General Merchandise Stores","reputation_class" => 2,],
["sic_code" => 54,"industry_title" => "Food Stores","reputation_class" => 3,],
["sic_code" => 55,"industry_title" => "Automative Dealers & Service Stations","reputation_class" => 3,],
["sic_code" => 56,"industry_title" => "Apparel & Accessory Stores","reputation_class" => 3,],
["sic_code" => 57,"industry_title" => "Furniture & Homefurnishings Stores","reputation_class" => 3,],
["sic_code" => 58,"industry_title" => "Eating & Drinking Places","reputation_class" => 3,],
["sic_code" => 59,"industry_title" => "Miscellaneous Retail","reputation_class" => 2,],
["sic_code" => 60,"industry_title" => "Depository Institutions","reputation_class" => 3,],
["sic_code" => 61,"industry_title" => "Nondepository Institutions","reputation_class" => 3,],
["sic_code" => 62,"industry_title" => "Security & Commodity Brokers","reputation_class" => 3,],
["sic_code" => 63,"industry_title" => "Insurance Carriers","reputation_class" => 3,],
["sic_code" => 64,"industry_title" => "Insurance Agents. Brokers. & Service","reputation_class" => 3,],
["sic_code" => 65,"industry_title" => "Real Estate","reputation_class" => 3,],
["sic_code" => 67,"industry_title" => "Holding & Other Investment Offices","reputation_class" => 1,],
["sic_code" => 70,"industry_title" => "Hotels & Other Lodging Places","reputation_class" => 3,],
["sic_code" => 72,"industry_title" => "Personal Services","reputation_class" => 3,],
["sic_code" => 73,"industry_title" => "Business Services","reputation_class" => 3,],
["sic_code" => 75,"industry_title" => "Auto Repair. Services. & Parking","reputation_class" => 3,],
["sic_code" => 76,"industry_title" => "Miscellaneous Repair Services","reputation_class" => 3,],
["sic_code" => 78,"industry_title" => "Motion Pictures","reputation_class" => 3,],
["sic_code" => 79,"industry_title" => "Amusement & Recreation Services","reputation_class" => 3,],
["sic_code" => 80,"industry_title" => "Health Services","reputation_class" => 3,],
["sic_code" => 81,"industry_title" => "Legal Services","reputation_class" => 3,],
["sic_code" => 82,"industry_title" => "Educational Services","reputation_class" => 2,],
["sic_code" => 83,"industry_title" => "Social Services","reputation_class" => 2,],
["sic_code" => 84,"industry_title" => "Museums. Botanical. Zoological Gardens","reputation_class" => 3,],
["sic_code" => 86,"industry_title" => "Membership Organizations","reputation_class" => 2,],
["sic_code" => 87,"industry_title" => "Engineering & Management Services","reputation_class" => 3,],
["sic_code" => 88,"industry_title" => "Private Households","reputation_class" => 1,],
["sic_code" => 89,"industry_title" => "Services. Not Elsewhere Classified","reputation_class" => 2,],
["sic_code" => 91,"industry_title" => "Public Executive. Legislative. & General","reputation_class" => 1,],
["sic_code" => 92,"industry_title" => "Public Justice. Public Order. & Safety","reputation_class" => 1,],
["sic_code" => 93,"industry_title" => "Public Finance. Taxation. & Monetary Policy","reputation_class" => 1,],
["sic_code" => 94,"industry_title" => "Public Administration of Human Resources","reputation_class" => 1,],
["sic_code" => 95,"industry_title" => "Public Environmental Quality & Housing","reputation_class" => 1,],
["sic_code" => 96,"industry_title" => "Public Administration of Economic Programs","reputation_class" => 1,],
["sic_code" => 97,"industry_title" => "National Security & International Affairs","reputation_class" => 1,],
["sic_code" => 98,"industry_title" => "Zoological Gardens","reputation_class" => 3,],
["sic_code" => 99,"industry_title" => "Non-Classifiable Establishments","reputation_class" => 2,],
];